// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYb-9_qNGD2y2zOmyqr6jEV16hCIBnpdc',
    appId: '1:954082180234:web:e9b2ea23fcdded646b4173',
    messagingSenderId: '954082180234',
    projectId: 'college-app-d31ae',
    authDomain: 'college-app-d31ae.firebaseapp.com',
    storageBucket: 'college-app-d31ae.appspot.com',
    measurementId: 'G-QT1BWQH72C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdLGjoP7pPI7HsyBk5bn55GGln30II17Q',
    appId: '1:954082180234:android:8360ac5f66beed1e6b4173',
    messagingSenderId: '954082180234',
    projectId: 'college-app-d31ae',
    storageBucket: 'college-app-d31ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8G6J1SyVAlzPkXPPky9STHhPQ8daCMxI',
    appId: '1:954082180234:ios:48355b2b8cdb40036b4173',
    messagingSenderId: '954082180234',
    projectId: 'college-app-d31ae',
    storageBucket: 'college-app-d31ae.appspot.com',
    iosBundleId: 'com.example.hogwartsCollegeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8G6J1SyVAlzPkXPPky9STHhPQ8daCMxI',
    appId: '1:954082180234:ios:48355b2b8cdb40036b4173',
    messagingSenderId: '954082180234',
    projectId: 'college-app-d31ae',
    storageBucket: 'college-app-d31ae.appspot.com',
    iosBundleId: 'com.example.hogwartsCollegeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYb-9_qNGD2y2zOmyqr6jEV16hCIBnpdc',
    appId: '1:954082180234:web:647f8324d2d4bb696b4173',
    messagingSenderId: '954082180234',
    projectId: 'college-app-d31ae',
    authDomain: 'college-app-d31ae.firebaseapp.com',
    storageBucket: 'college-app-d31ae.appspot.com',
    measurementId: 'G-YYR66H6F0P',
  );
}
